<a href="https://colab.research.google.com/github/muneeswarikagitala-web/datascience-and-ml/blob/main/aggregate_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
import pandas as pd
# Load dataset
df = sns.load_dataset("tips")
# Display first 5 rows
print(df.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [2]:
df["total_bill"].sum()

np.float64(4827.77)

In [3]:
df["tip"].mean()

np.float64(2.99827868852459)

In [4]:

df["total_bill"].max()

50.81

In [5]:
df["tip"].min()

1.0

In [6]:
total_rows = df.count()
print(total_rows)

total_bill    244
tip           244
sex           244
smoker        244
day           244
time          244
size          244
dtype: int64

In [7]:
df['total_bill'].median()

17.795

In [8]:
df['tip'].std()

1.3836381890011826

In [9]:
df['total_bill'].var()

79.25293861397826

In [10]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [11]:
df['total_bill'].agg(['mean', 'max', 'min'])

mean    19.785943
max     50.810000
min      3.070000
Name: total_bill, dtype: float64